apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
spec:
  selector:
    matchLabels:
      app: configserver
  replicas: 1
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: emreoytun/config-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8079  # Updated to match the application's port
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: configserver-ssvc
spec:
  selector:
    app: configserver
  ports:
    - protocol: "TCP"
      port: 80             # Port exposed by the service
      targetPort: 8079     # Port on which the application is listening
  type: LoadBalancer
